### ISSUE TITLE
Backend Todo list

### ISSUE THREAD

**Issue by howard9199** [JacobLinCool/Bang-C#67]
GM: 每一個狀態改變call jsonify
jsonify: Game 轉為json，並把這個使用者要屏蔽的訊息屏蔽
handle action: check前端的牌的pointer有沒有在裡面
GM一次傳多筆資料給server，之後改變狀態。
資料要存有幾筆資料。

Todo List:

- [x] jsonify @MakerTakala 
- [x] GM call jsonify
- [x] handle_action @howard9199 
- [x] GM receive from handle_action
